/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/public'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAiPredictionRouteImport } from './routes/app.ai-prediction'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppApiCenterRouteImport } from './routes/app.api-center'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppBottlenecksRouteImport } from './routes/app.bottlenecks'
import { Route as AppCompareRouteImport } from './routes/app.compare'
import { Route as AppCompensationRouteImport } from './routes/app.compensation'
import { Route as AppContinuousLearningRouteImport } from './routes/app.continuous-learning'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppDataRouteImport } from './routes/app.data'
import { Route as AppDistrictAnalyticsRouteImport } from './routes/app.district-analytics'
import { Route as AppDocumentationRouteImport } from './routes/app.documentation'
import { Route as AppGisRouteImport } from './routes/app.gis'
import { Route as AppInterventionsRouteImport } from './routes/app.interventions'
import { Route as AppLandPriceRouteImport } from './routes/app.land-price'
import { Route as AppLegalRouteImport } from './routes/app.legal'
import { Route as AppModelRouteImport } from './routes/app.model'
import { Route as AppPossessionRouteImport } from './routes/app.possession'
import { Route as AppPredictorRouteImport } from './routes/app.predictor'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRrRouteImport } from './routes/app.rr'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppStakeholdersRouteImport } from './routes/app.stakeholders'
import { Route as AppStateAnalyticsRouteImport } from './routes/app.state-analytics'
import { Route as AppTimelineRouteImport } from './routes/app.timeline'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as PublicIndexRouteImport } from './routes/public.index'
import { Route as PublicAboutRouteImport } from './routes/public.about'
import { Route as PublicImpactRouteImport } from './routes/public.impact'
import { Route as PublicMapRouteImport } from './routes/public.map'
import { Route as PublicMethodologyRouteImport } from './routes/public.methodology'
import { Route as PublicNoticesRouteImport } from './routes/public.notices'
import { Route as PublicStatisticsRouteImport } from './routes/public.statistics'
import { Route as AppProjectsIndexRouteImport } from './routes/app.projects.index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app.projects.$projectId'
import { Route as AppProjectsNewRouteImport } from './routes/app.projects.new'
import { Route as PublicProjectsIndexRouteImport } from './routes/public.projects.index'
import { Route as PublicProjectsProjectIdRouteImport } from './routes/public.projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiPredictionRoute = AppAiPredictionRouteImport.update({
  id: '/ai-prediction',
  path: '/ai-prediction',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppApiCenterRoute = AppApiCenterRouteImport.update({
  id: '/api-center',
  path: '/api-center',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppBottlenecksRoute = AppBottlenecksRouteImport.update({
  id: '/bottlenecks',
  path: '/bottlenecks',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppCompensationRoute = AppCompensationRouteImport.update({
  id: '/compensation',
  path: '/compensation',
  getParentRoute: () => AppRoute,
} as any)
const AppContinuousLearningRoute = AppContinuousLearningRouteImport.update({
  id: '/continuous-learning',
  path: '/continuous-learning',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRoute,
} as any)
const AppDistrictAnalyticsRoute = AppDistrictAnalyticsRouteImport.update({
  id: '/district-analytics',
  path: '/district-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentationRoute = AppDocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => AppRoute,
} as any)
const AppGisRoute = AppGisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => AppRoute,
} as any)
const AppInterventionsRoute = AppInterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => AppRoute,
} as any)
const AppLandPriceRoute = AppLandPriceRouteImport.update({
  id: '/land-price',
  path: '/land-price',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalRoute = AppLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AppRoute,
} as any)
const AppModelRoute = AppModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => AppRoute,
} as any)
const AppPossessionRoute = AppPossessionRouteImport.update({
  id: '/possession',
  path: '/possession',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictorRoute = AppPredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRrRoute = AppRrRouteImport.update({
  id: '/rr',
  path: '/rr',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStakeholdersRoute = AppStakeholdersRouteImport.update({
  id: '/stakeholders',
  path: '/stakeholders',
  getParentRoute: () => AppRoute,
} as any)
const AppStateAnalyticsRoute = AppStateAnalyticsRouteImport.update({
  id: '/state-analytics',
  path: '/state-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicImpactRoute = PublicImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMapRoute = PublicMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMethodologyRoute = PublicMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNoticesRoute = PublicNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => PublicRoute,
} as any)
const PublicStatisticsRoute = PublicStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => PublicRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const PublicProjectsIndexRoute = PublicProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProjectsProjectIdRoute = PublicProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/public': typeof PublicRouteWithChildren
  '/app/ai-prediction': typeof AppAiPredictionRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/api-center': typeof AppApiCenterRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bottlenecks': typeof AppBottlenecksRoute
  '/app/compare': typeof AppCompareRoute
  '/app/compensation': typeof AppCompensationRoute
  '/app/continuous-learning': typeof AppContinuousLearningRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/data': typeof AppDataRoute
  '/app/district-analytics': typeof AppDistrictAnalyticsRoute
  '/app/documentation': typeof AppDocumentationRoute
  '/app/gis': typeof AppGisRoute
  '/app/interventions': typeof AppInterventionsRoute
  '/app/land-price': typeof AppLandPriceRoute
  '/app/legal': typeof AppLegalRoute
  '/app/model': typeof AppModelRoute
  '/app/possession': typeof AppPossessionRoute
  '/app/predictor': typeof AppPredictorRoute
  '/app/reports': typeof AppReportsRoute
  '/app/rr': typeof AppRrRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stakeholders': typeof AppStakeholdersRoute
  '/app/state-analytics': typeof AppStateAnalyticsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/users': typeof AppUsersRoute
  '/public/about': typeof PublicAboutRoute
  '/public/impact': typeof PublicImpactRoute
  '/public/map': typeof PublicMapRoute
  '/public/methodology': typeof PublicMethodologyRoute
  '/public/notices': typeof PublicNoticesRoute
  '/public/statistics': typeof PublicStatisticsRoute
  '/app/': typeof AppIndexRoute
  '/public/': typeof PublicIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/public/projects/$projectId': typeof PublicProjectsProjectIdRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/public/projects/': typeof PublicProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/ai-prediction': typeof AppAiPredictionRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/api-center': typeof AppApiCenterRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bottlenecks': typeof AppBottlenecksRoute
  '/app/compare': typeof AppCompareRoute
  '/app/compensation': typeof AppCompensationRoute
  '/app/continuous-learning': typeof AppContinuousLearningRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/data': typeof AppDataRoute
  '/app/district-analytics': typeof AppDistrictAnalyticsRoute
  '/app/documentation': typeof AppDocumentationRoute
  '/app/gis': typeof AppGisRoute
  '/app/interventions': typeof AppInterventionsRoute
  '/app/land-price': typeof AppLandPriceRoute
  '/app/legal': typeof AppLegalRoute
  '/app/model': typeof AppModelRoute
  '/app/possession': typeof AppPossessionRoute
  '/app/predictor': typeof AppPredictorRoute
  '/app/reports': typeof AppReportsRoute
  '/app/rr': typeof AppRrRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stakeholders': typeof AppStakeholdersRoute
  '/app/state-analytics': typeof AppStateAnalyticsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/users': typeof AppUsersRoute
  '/public/about': typeof PublicAboutRoute
  '/public/impact': typeof PublicImpactRoute
  '/public/map': typeof PublicMapRoute
  '/public/methodology': typeof PublicMethodologyRoute
  '/public/notices': typeof PublicNoticesRoute
  '/public/statistics': typeof PublicStatisticsRoute
  '/app': typeof AppIndexRoute
  '/public': typeof PublicIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/public/projects/$projectId': typeof PublicProjectsProjectIdRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/public/projects': typeof PublicProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/public': typeof PublicRouteWithChildren
  '/app/ai-prediction': typeof AppAiPredictionRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/api-center': typeof AppApiCenterRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bottlenecks': typeof AppBottlenecksRoute
  '/app/compare': typeof AppCompareRoute
  '/app/compensation': typeof AppCompensationRoute
  '/app/continuous-learning': typeof AppContinuousLearningRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/data': typeof AppDataRoute
  '/app/district-analytics': typeof AppDistrictAnalyticsRoute
  '/app/documentation': typeof AppDocumentationRoute
  '/app/gis': typeof AppGisRoute
  '/app/interventions': typeof AppInterventionsRoute
  '/app/land-price': typeof AppLandPriceRoute
  '/app/legal': typeof AppLegalRoute
  '/app/model': typeof AppModelRoute
  '/app/possession': typeof AppPossessionRoute
  '/app/predictor': typeof AppPredictorRoute
  '/app/reports': typeof AppReportsRoute
  '/app/rr': typeof AppRrRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stakeholders': typeof AppStakeholdersRoute
  '/app/state-analytics': typeof AppStateAnalyticsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/users': typeof AppUsersRoute
  '/public/about': typeof PublicAboutRoute
  '/public/impact': typeof PublicImpactRoute
  '/public/map': typeof PublicMapRoute
  '/public/methodology': typeof PublicMethodologyRoute
  '/public/notices': typeof PublicNoticesRoute
  '/public/statistics': typeof PublicStatisticsRoute
  '/app/': typeof AppIndexRoute
  '/public/': typeof PublicIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/public/projects/$projectId': typeof PublicProjectsProjectIdRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/public/projects/': typeof PublicProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/public'
    | '/app/ai-prediction'
    | '/app/alerts'
    | '/app/api-center'
    | '/app/audit'
    | '/app/bottlenecks'
    | '/app/compare'
    | '/app/compensation'
    | '/app/continuous-learning'
    | '/app/dashboard'
    | '/app/data'
    | '/app/district-analytics'
    | '/app/documentation'
    | '/app/gis'
    | '/app/interventions'
    | '/app/land-price'
    | '/app/legal'
    | '/app/model'
    | '/app/possession'
    | '/app/predictor'
    | '/app/reports'
    | '/app/rr'
    | '/app/settings'
    | '/app/stakeholders'
    | '/app/state-analytics'
    | '/app/timeline'
    | '/app/users'
    | '/public/about'
    | '/public/impact'
    | '/public/map'
    | '/public/methodology'
    | '/public/notices'
    | '/public/statistics'
    | '/app/'
    | '/public/'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/public/projects/$projectId'
    | '/app/projects/'
    | '/public/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/ai-prediction'
    | '/app/alerts'
    | '/app/api-center'
    | '/app/audit'
    | '/app/bottlenecks'
    | '/app/compare'
    | '/app/compensation'
    | '/app/continuous-learning'
    | '/app/dashboard'
    | '/app/data'
    | '/app/district-analytics'
    | '/app/documentation'
    | '/app/gis'
    | '/app/interventions'
    | '/app/land-price'
    | '/app/legal'
    | '/app/model'
    | '/app/possession'
    | '/app/predictor'
    | '/app/reports'
    | '/app/rr'
    | '/app/settings'
    | '/app/stakeholders'
    | '/app/state-analytics'
    | '/app/timeline'
    | '/app/users'
    | '/public/about'
    | '/public/impact'
    | '/public/map'
    | '/public/methodology'
    | '/public/notices'
    | '/public/statistics'
    | '/app'
    | '/public'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/public/projects/$projectId'
    | '/app/projects'
    | '/public/projects'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/public'
    | '/app/ai-prediction'
    | '/app/alerts'
    | '/app/api-center'
    | '/app/audit'
    | '/app/bottlenecks'
    | '/app/compare'
    | '/app/compensation'
    | '/app/continuous-learning'
    | '/app/dashboard'
    | '/app/data'
    | '/app/district-analytics'
    | '/app/documentation'
    | '/app/gis'
    | '/app/interventions'
    | '/app/land-price'
    | '/app/legal'
    | '/app/model'
    | '/app/possession'
    | '/app/predictor'
    | '/app/reports'
    | '/app/rr'
    | '/app/settings'
    | '/app/stakeholders'
    | '/app/state-analytics'
    | '/app/timeline'
    | '/app/users'
    | '/public/about'
    | '/public/impact'
    | '/public/map'
    | '/public/methodology'
    | '/public/notices'
    | '/public/statistics'
    | '/app/'
    | '/public/'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/public/projects/$projectId'
    | '/app/projects/'
    | '/public/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-prediction': {
      id: '/app/ai-prediction'
      path: '/ai-prediction'
      fullPath: '/app/ai-prediction'
      preLoaderRoute: typeof AppAiPredictionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/api-center': {
      id: '/app/api-center'
      path: '/api-center'
      fullPath: '/app/api-center'
      preLoaderRoute: typeof AppApiCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bottlenecks': {
      id: '/app/bottlenecks'
      path: '/bottlenecks'
      fullPath: '/app/bottlenecks'
      preLoaderRoute: typeof AppBottlenecksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compare': {
      id: '/app/compare'
      path: '/compare'
      fullPath: '/app/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compensation': {
      id: '/app/compensation'
      path: '/compensation'
      fullPath: '/app/compensation'
      preLoaderRoute: typeof AppCompensationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/continuous-learning': {
      id: '/app/continuous-learning'
      path: '/continuous-learning'
      fullPath: '/app/continuous-learning'
      preLoaderRoute: typeof AppContinuousLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data': {
      id: '/app/data'
      path: '/data'
      fullPath: '/app/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/district-analytics': {
      id: '/app/district-analytics'
      path: '/district-analytics'
      fullPath: '/app/district-analytics'
      preLoaderRoute: typeof AppDistrictAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documentation': {
      id: '/app/documentation'
      path: '/documentation'
      fullPath: '/app/documentation'
      preLoaderRoute: typeof AppDocumentationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gis': {
      id: '/app/gis'
      path: '/gis'
      fullPath: '/app/gis'
      preLoaderRoute: typeof AppGisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interventions': {
      id: '/app/interventions'
      path: '/interventions'
      fullPath: '/app/interventions'
      preLoaderRoute: typeof AppInterventionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/land-price': {
      id: '/app/land-price'
      path: '/land-price'
      fullPath: '/app/land-price'
      preLoaderRoute: typeof AppLandPriceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/legal': {
      id: '/app/legal'
      path: '/legal'
      fullPath: '/app/legal'
      preLoaderRoute: typeof AppLegalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/model': {
      id: '/app/model'
      path: '/model'
      fullPath: '/app/model'
      preLoaderRoute: typeof AppModelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/possession': {
      id: '/app/possession'
      path: '/possession'
      fullPath: '/app/possession'
      preLoaderRoute: typeof AppPossessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/predictor': {
      id: '/app/predictor'
      path: '/predictor'
      fullPath: '/app/predictor'
      preLoaderRoute: typeof AppPredictorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rr': {
      id: '/app/rr'
      path: '/rr'
      fullPath: '/app/rr'
      preLoaderRoute: typeof AppRrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stakeholders': {
      id: '/app/stakeholders'
      path: '/stakeholders'
      fullPath: '/app/stakeholders'
      preLoaderRoute: typeof AppStakeholdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/state-analytics': {
      id: '/app/state-analytics'
      path: '/state-analytics'
      fullPath: '/app/state-analytics'
      preLoaderRoute: typeof AppStateAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timeline': {
      id: '/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/public/': {
      id: '/public/'
      path: '/'
      fullPath: '/public/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/about': {
      id: '/public/about'
      path: '/about'
      fullPath: '/public/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/impact': {
      id: '/public/impact'
      path: '/impact'
      fullPath: '/public/impact'
      preLoaderRoute: typeof PublicImpactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/map': {
      id: '/public/map'
      path: '/map'
      fullPath: '/public/map'
      preLoaderRoute: typeof PublicMapRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/methodology': {
      id: '/public/methodology'
      path: '/methodology'
      fullPath: '/public/methodology'
      preLoaderRoute: typeof PublicMethodologyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/notices': {
      id: '/public/notices'
      path: '/notices'
      fullPath: '/public/notices'
      preLoaderRoute: typeof PublicNoticesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/statistics': {
      id: '/public/statistics'
      path: '/statistics'
      fullPath: '/public/statistics'
      preLoaderRoute: typeof PublicStatisticsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/new': {
      id: '/app/projects/new'
      path: '/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/public/projects/': {
      id: '/public/projects/'
      path: '/projects'
      fullPath: '/public/projects/'
      preLoaderRoute: typeof PublicProjectsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/projects/$projectId': {
      id: '/public/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/public/projects/$projectId'
      preLoaderRoute: typeof PublicProjectsProjectIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AppRouteChildren {
  AppAiPredictionRoute: typeof AppAiPredictionRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppApiCenterRoute: typeof AppApiCenterRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBottlenecksRoute: typeof AppBottlenecksRoute
  AppCompareRoute: typeof AppCompareRoute
  AppCompensationRoute: typeof AppCompensationRoute
  AppContinuousLearningRoute: typeof AppContinuousLearningRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDataRoute: typeof AppDataRoute
  AppDistrictAnalyticsRoute: typeof AppDistrictAnalyticsRoute
  AppDocumentationRoute: typeof AppDocumentationRoute
  AppGisRoute: typeof AppGisRoute
  AppInterventionsRoute: typeof AppInterventionsRoute
  AppLandPriceRoute: typeof AppLandPriceRoute
  AppLegalRoute: typeof AppLegalRoute
  AppModelRoute: typeof AppModelRoute
  AppPossessionRoute: typeof AppPossessionRoute
  AppPredictorRoute: typeof AppPredictorRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRrRoute: typeof AppRrRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStakeholdersRoute: typeof AppStakeholdersRoute
  AppStateAnalyticsRoute: typeof AppStateAnalyticsRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiPredictionRoute: AppAiPredictionRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppApiCenterRoute: AppApiCenterRoute,
  AppAuditRoute: AppAuditRoute,
  AppBottlenecksRoute: AppBottlenecksRoute,
  AppCompareRoute: AppCompareRoute,
  AppCompensationRoute: AppCompensationRoute,
  AppContinuousLearningRoute: AppContinuousLearningRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDataRoute: AppDataRoute,
  AppDistrictAnalyticsRoute: AppDistrictAnalyticsRoute,
  AppDocumentationRoute: AppDocumentationRoute,
  AppGisRoute: AppGisRoute,
  AppInterventionsRoute: AppInterventionsRoute,
  AppLandPriceRoute: AppLandPriceRoute,
  AppLegalRoute: AppLegalRoute,
  AppModelRoute: AppModelRoute,
  AppPossessionRoute: AppPossessionRoute,
  AppPredictorRoute: AppPredictorRoute,
  AppReportsRoute: AppReportsRoute,
  AppRrRoute: AppRrRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStakeholdersRoute: AppStakeholdersRoute,
  AppStateAnalyticsRoute: AppStateAnalyticsRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicImpactRoute: typeof PublicImpactRoute
  PublicMapRoute: typeof PublicMapRoute
  PublicMethodologyRoute: typeof PublicMethodologyRoute
  PublicNoticesRoute: typeof PublicNoticesRoute
  PublicStatisticsRoute: typeof PublicStatisticsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicProjectsProjectIdRoute: typeof PublicProjectsProjectIdRoute
  PublicProjectsIndexRoute: typeof PublicProjectsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicImpactRoute: PublicImpactRoute,
  PublicMapRoute: PublicMapRoute,
  PublicMethodologyRoute: PublicMethodologyRoute,
  PublicNoticesRoute: PublicNoticesRoute,
  PublicStatisticsRoute: PublicStatisticsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicProjectsProjectIdRoute: PublicProjectsProjectIdRoute,
  PublicProjectsIndexRoute: PublicProjectsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
