/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/public'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppDataRouteImport } from './routes/app.data'
import { Route as AppGisRouteImport } from './routes/app.gis'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppModelRouteImport } from './routes/app.model'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as PublicIndexRouteImport } from './routes/public.index'
import { Route as PublicAboutRouteImport } from './routes/public.about'
import { Route as PublicMapRouteImport } from './routes/public.map'
import { Route as PublicNoticesRouteImport } from './routes/public.notices'
import { Route as PublicStatisticsRouteImport } from './routes/public.statistics'
import { Route as AppProjectsIndexRouteImport } from './routes/app.projects.index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app.projects.$projectId'
import { Route as AppProjectsNewRouteImport } from './routes/app.projects.new'
import { Route as PublicProjectsIndexRouteImport } from './routes/public.projects.index'
import { Route as PublicProjectsProjectIdRouteImport } from './routes/public.projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRoute,
} as any)
const AppGisRoute = AppGisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppModelRoute = AppModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMapRoute = PublicMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNoticesRoute = PublicNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => PublicRoute,
} as any)
const PublicStatisticsRoute = PublicStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => PublicRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const PublicProjectsIndexRoute = PublicProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProjectsProjectIdRoute = PublicProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/public': typeof PublicRouteWithChildren
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/data': typeof AppDataRoute
  '/app/gis': typeof AppGisRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/model': typeof AppModelRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/public/about': typeof PublicAboutRoute
  '/public/map': typeof PublicMapRoute
  '/public/notices': typeof PublicNoticesRoute
  '/public/statistics': typeof PublicStatisticsRoute
  '/app/': typeof AppIndexRoute
  '/public/': typeof PublicIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/public/projects/$projectId': typeof PublicProjectsProjectIdRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/public/projects/': typeof PublicProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/data': typeof AppDataRoute
  '/app/gis': typeof AppGisRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/model': typeof AppModelRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/public/about': typeof PublicAboutRoute
  '/public/map': typeof PublicMapRoute
  '/public/notices': typeof PublicNoticesRoute
  '/public/statistics': typeof PublicStatisticsRoute
  '/app': typeof AppIndexRoute
  '/public': typeof PublicIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/public/projects/$projectId': typeof PublicProjectsProjectIdRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/public/projects': typeof PublicProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/public': typeof PublicRouteWithChildren
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/data': typeof AppDataRoute
  '/app/gis': typeof AppGisRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/model': typeof AppModelRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/public/about': typeof PublicAboutRoute
  '/public/map': typeof PublicMapRoute
  '/public/notices': typeof PublicNoticesRoute
  '/public/statistics': typeof PublicStatisticsRoute
  '/app/': typeof AppIndexRoute
  '/public/': typeof PublicIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/public/projects/$projectId': typeof PublicProjectsProjectIdRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/public/projects/': typeof PublicProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/public'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/data'
    | '/app/gis'
    | '/app/insights'
    | '/app/model'
    | '/app/reports'
    | '/app/settings'
    | '/app/users'
    | '/public/about'
    | '/public/map'
    | '/public/notices'
    | '/public/statistics'
    | '/app/'
    | '/public/'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/public/projects/$projectId'
    | '/app/projects/'
    | '/public/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/data'
    | '/app/gis'
    | '/app/insights'
    | '/app/model'
    | '/app/reports'
    | '/app/settings'
    | '/app/users'
    | '/public/about'
    | '/public/map'
    | '/public/notices'
    | '/public/statistics'
    | '/app'
    | '/public'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/public/projects/$projectId'
    | '/app/projects'
    | '/public/projects'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/public'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/data'
    | '/app/gis'
    | '/app/insights'
    | '/app/model'
    | '/app/reports'
    | '/app/settings'
    | '/app/users'
    | '/public/about'
    | '/public/map'
    | '/public/notices'
    | '/public/statistics'
    | '/app/'
    | '/public/'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/public/projects/$projectId'
    | '/app/projects/'
    | '/public/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data': {
      id: '/app/data'
      path: '/data'
      fullPath: '/app/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gis': {
      id: '/app/gis'
      path: '/gis'
      fullPath: '/app/gis'
      preLoaderRoute: typeof AppGisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/model': {
      id: '/app/model'
      path: '/model'
      fullPath: '/app/model'
      preLoaderRoute: typeof AppModelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/public/': {
      id: '/public/'
      path: '/'
      fullPath: '/public/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/about': {
      id: '/public/about'
      path: '/about'
      fullPath: '/public/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/map': {
      id: '/public/map'
      path: '/map'
      fullPath: '/public/map'
      preLoaderRoute: typeof PublicMapRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/notices': {
      id: '/public/notices'
      path: '/notices'
      fullPath: '/public/notices'
      preLoaderRoute: typeof PublicNoticesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/statistics': {
      id: '/public/statistics'
      path: '/statistics'
      fullPath: '/public/statistics'
      preLoaderRoute: typeof PublicStatisticsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/new': {
      id: '/app/projects/new'
      path: '/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/public/projects/': {
      id: '/public/projects/'
      path: '/projects'
      fullPath: '/public/projects/'
      preLoaderRoute: typeof PublicProjectsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/projects/$projectId': {
      id: '/public/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/public/projects/$projectId'
      preLoaderRoute: typeof PublicProjectsProjectIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDataRoute: typeof AppDataRoute
  AppGisRoute: typeof AppGisRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppModelRoute: typeof AppModelRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDataRoute: AppDataRoute,
  AppGisRoute: AppGisRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppModelRoute: AppModelRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicMapRoute: typeof PublicMapRoute
  PublicNoticesRoute: typeof PublicNoticesRoute
  PublicStatisticsRoute: typeof PublicStatisticsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicProjectsProjectIdRoute: typeof PublicProjectsProjectIdRoute
  PublicProjectsIndexRoute: typeof PublicProjectsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicMapRoute: PublicMapRoute,
  PublicNoticesRoute: PublicNoticesRoute,
  PublicStatisticsRoute: PublicStatisticsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicProjectsProjectIdRoute: PublicProjectsProjectIdRoute,
  PublicProjectsIndexRoute: PublicProjectsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
